image: java:8-jdk

stages:
- validate
- build
- review
#- pages
- deploy

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
- export GRADLE_USER_HOME=`pwd`/.gradle
- rm -f  .gradle/caches/modules-2/modules-2.lock
- rm -fr .gradle/caches/*/plugin-resolution/

# Cache downloaded dependencies and plugins between builds.
cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches
  - target/

validate:
  stage: validate
  script:
  - ./gradlew check

build:
  stage: build
  script:
  - ./gradlew clean
  - ./gradlew compileWithDependencies #rename?!
  artifacts:
    expire_in: 1 week
    paths:
    - target/*.jar

deploy:master:
  stage: deploy
  script:
  - './gradlew uploadArchives -PnexusUsername=$PACKAGES_USER -PnexusPassword=$PACKAGES_PASSWORD'
  only:
  - master@craftmania/crafteconomy
  when: manual

deploy:release:
  stage: deploy
  script:
  - './gradlew uploadArchives -PnexusUsername=$PACKAGES_USER -PnexusPassword=$PACKAGES_PASSWORD'
  only:
  - tags

sast:
  stage: review
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  tags:
  - privileged
  services:
  - docker:stable-dind
  script:
  - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
  - docker run
      --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}"
      --volume "$PWD:/code"
      --volume /var/run/docker.sock:/var/run/docker.sock
      "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
  artifacts:
    reports:
      sast: gl-sast-report.json