# Napojeni na SQL
sql:
  hostname: host
  port: 3306
  database: database
  username: user
  password: password

# Nastaveni SQL
settings:
  minimumConnections: 2
  maximumConnections: 5
  timeout: 30000

# Registrace profilu do Ccomunity (pouze lobby)
registerEnabled: false

# Id serveru
server: survival

# Integrace a zasílání exceptions na Sentry
sentry-dsn: ''

# Nastavení pro globální ekonomiku
economy:

  # VoteTokens verze se liší dle verze serveru
  # VoteTokens v1 -> 1.9+
  # VoteTokens v2 -> 1.14+
  # VoteTokens v3 -> 1.18+
  votetokens-version: 2

# Deaktivace určitých věcí z důvodu testů a různých nastavení na serverech
disables:
  achievement-log: false
  achievement-points: false
  achievement-experience: false
  global-level-updates: false

# Nahodne davani expu za urceny cas
random-exp:
  enabled: false
  settings:
    every: 5 # Jak často v minutách
    min: 30
    max: 60
  not-in-world:
    - spawn

# Pokud mají být zapnuty příkazy jako /money, /eco atd
vault-economy:
  enabled: false
  name: "$"
  min-confirm: 1000
  start-value: 0 # Hodnota, s kterou hráč začne
  cleanup:
    enabled: false
    days: 150
  tax-payments: # Každo týdenní placení poplatků serveru
    enabled: false
    min-balance: 150000
    percentage: 5