# Napojeni na SQL
sql:
  hostname: host
  port: 3306
  database: database
  username: user
  password: password

# Nastaveni SQL
settings:
  minimumConnections: 2
  maximumConnections: 5
  timeout: 30000

# Registrace profilu do Ccomunity (pouze lobby)
registerEnabled: false

# Nahodne davani expu za urceny cas
random-exp:
  enabled: false
  settings:
    every: 6000
    min: 30
    max: 60