# Napojeni na SQL
sql:
  hostname: host
  port: 3306
  database: database
  username: user
  password: password

# Nastaveni SQL
settings:
  minimumConnections: 2
  maximumConnections: 5
  timeout: 30000

# Registrace profilu do Ccomunity (pouze lobby)
registerEnabled: false

# Id serveru
server: survival

# Integrace a zasílání exceptions na Sentry
sentry-dsn: ''

# Deaktivace určitých věcí z důvodu testů a různých nastavení na serverech
disables:
  achievement-log: false
  achievement-points: false
  achievement-experience: false
  global-level-updates: false

# Nahodne davani expu za urceny cas
random-exp:
  enabled: false
  settings:
    every: 6000
    min: 30
    max: 60

# Pokud mají být zapnuty příkazy jako /money, /eco atd
vault-economy:
  enabled: false
  name: "$"