name: CraftEconomy
version: '1.4.1'
description: Economy plugin for Craftmania.cz
author: MrWakeCZ
main: cz.craftmania.crafteconomy.Main
depend: [CraftCore,CraftLibs]
softdepend: [Vault]
loadbefore: [TradeMe,ShopGUIPlus,SellStick,UltraMinions,QuickShop,BentoBox,AuctionGUIPlus]
api-version: '1.16'

permissions:
  crafteconomy.*:
    description: Prava ku vsem prikazum
    children:
      crafteconomy.admin: true