name: CraftEconomy
version: '2.1.0'
description: Economy plugin for Craftmania.cz
author: MrWakeCZ
main: cz.craftmania.crafteconomy.Main
load: POSTWORLD
depend:
  - CraftCore
  - CraftLibs
  - Vault
softdepend:
  - LuxuryQuests
loadbefore:
  - QuickShop
  - CMI
  - TradeMe
  - ShopGUIPlus
  - SellStick
  - UltraMinions
  - AuctionGUIPlus
  - DeluxeCombat
api-version: '1.17'

permissions:
  crafteconomy.*:
    description: Prava ku vsem prikazum
    children:
      crafteconomy.admin: true