name: CraftEconomy
version: '1.3.7'
description: Economy plugin for Craftmania.cz
author: MrWakeCZ
main: cz.craftmania.crafteconomy.Main
softdepend: [MVdWPlaceholderAPI,AdvancedAchievements,CraftCore,CommandAPI,CMI,Vault,CraftLibs]
loadbefore: [TradeMe,ShopGUIPlus,SellStick,UltraMinions]
api-version: '1.15'

permissions:
  crafteconomy.*:
    description: Prava ku vsem prikazum
    children:
      crafteconomy.admin: true