name: CraftEconomy
version: '${version}'
description: Economy plugin for Craftmania.cz
author: MrWakeCZ
main: cz.craftmania.crafteconomy.Main
load: POSTWORLD
depend:
  - CraftCore
  - CraftLibs
  - Vault
softdepend:
  - LuxuryQuests
  - PlaceholderAPI
loadbefore:
  - QuickShop
  - CMI
  - TradeMe
  - ShopGUIPlus
  - SellStick
  - UltraMinions
  - AuctionGUIPlus
  - DeluxeCombat
  - CrazyCrates
api-version: '1.17'

permissions:
  crafteconomy.*:
    description: Prava ku vsem prikazum
    children:
      crafteconomy.admin: true