name: CraftEconomy
version: '1.3.0-beta'
description: Economy plugin for Craftmania.cz
author: MrWakeCZ
main: cz.craftmania.crafteconomy.Main
softdepend: [MVdWPlaceholderAPI,AdvancedAchievements,CraftCore,CommandAPI,CMI]
api-version: '1.13'

permissions:
  crafteconomy.*:
    description: Prava ku vsem prikazum
    children:
      crafteconomy.admin: true