name: CraftEconomy
version: 1.0.0
description: Economy plugin for Craftmania.cz
author: MrWakeCZ
main: cz.craftmania.crafteconomy.Main

commands:
  craftcoins:
    description: Zakladni prikaz na CraftCoiny
    aliases: [cc, coins]
  crafttokens:
    description: Zakladni prikaz na CraftTokeny
    aliases: [ct, tokens]
  votetokens:
    description: Zakladni prikaz na VoteTokeny
    aliases: [vt, vtokens]
  level:
    description: Globalní ranky