name: CraftEconomy
version: 1.1.0
description: Economy plugin for Craftmania.cz
author: MrWakeCZ
main: cz.craftmania.crafteconomy.Main
softdepend: [MVdWPlaceholderAPI]
depend: [CommandAPI]
api-version: '1.14'

permissions:
  crafteconomy.*:
    description: Prava ku vsem prikazum
    children:
      crafteconomy.admin: true