name: CraftEconomy
version: '1.4.0-snapshot'
description: Economy plugin for Craftmania.cz
author: MrWakeCZ
main: cz.craftmania.crafteconomy.Main
softdepend: [MVdWPlaceholderAPI,AdvancedAchievements,CraftCore,CommandAPI,CMI,Vault,CraftLibs,LuxuryQuests]
loadbefore: [TradeMe,ShopGUIPlus,SellStick,UltraMinions]
api-version: '1.16'

permissions:
  crafteconomy.*:
    description: Prava ku vsem prikazum
    children:
      crafteconomy.admin: true