package cz.craftmania.crafteconomy.objects;

public enum LevelType {

    // Levels and experience
    GLOBAL_LEVEL,
    GLOBAL_EXPERIENCE,

    SURVIVAL_LEVEL,
    SURVIVAL_EXPERIENCE,

    SKYBLOCK_LEVEL,
    SKYBLOCK_EXPERIENCE,

    CREATIVE_LEVEL,
    CREATIVE_EXPERIENCE,

    PRISON_LEVEL,
    PRISON_EXPERIENCE,

    VANILLA_LEVEL,
    VANILLA_EXPERIENCE,

    SKYCLOUD_LEVEL,
    SKYCLOUD_EXPERIENCE,
    
    HARDCORE_VANILLA_LEVEL,
    HARDCORE_VANILLA_EXPERIENCE,
    ;

    LevelType() {
    }
}
